# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  anywr-postgresql:
    container_name: local_pgdb
    image: postgres:14.5
    environment:
      - POSTGRES_USER=anywr
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ahmadou2808@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
